// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.Data;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524233448_MudancaValorImagens")]
    partial class MudancaValorImagens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("back_end.Models.Catalogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dt_adicionado")
                        .HasColumnType("date");

                    b.Property<int>("id_jpjogos")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("id_jpjogos");

                    b.HasIndex("id_user");

                    b.ToTable("Catalogos");
                });

            modelBuilder.Entity("back_end.Models.Conquista", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("banner_conquista")
                        .HasColumnType("longtext");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("id_jp")
                        .HasColumnType("int");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_jp");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("back_end.Models.Funcionario", b =>
                {
                    b.Property<int>("rf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("rf"));

                    b.Property<string>("acesso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cpf")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("rf");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("back_end.Models.Jogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("banner_jogo")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_jogo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("jogo");
                });

            modelBuilder.Entity("back_end.Models.JogoPlataforma", b =>
                {
                    b.Property<int>("id_jpjogos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_jpjogos"));

                    b.Property<int>("id_jogo")
                        .HasColumnType("int");

                    b.Property<int>("id_plataforma")
                        .HasColumnType("int");

                    b.HasKey("id_jpjogos");

                    b.HasIndex("id_jogo");

                    b.HasIndex("id_plataforma");

                    b.ToTable("JogosPlataformas");
                });

            modelBuilder.Entity("back_end.Models.Plataforma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("plataforma");
                });

            modelBuilder.Entity("back_end.Models.Seguidor", b =>
                {
                    b.Property<int>("id_seguidor")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_seguindo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_seguidor", "id_seguindo");

                    b.HasIndex("id_seguindo");

                    b.ToTable("Seguidores");
                });

            modelBuilder.Entity("back_end.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("banner_perfil")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("banner_perfil");

                    b.Property<DateTime>("dt_nasc")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("foto_perfil")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("back_end.Models.UsuarioConexao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("id_plataforma")
                        .HasColumnType("int")
                        .HasColumnName("id_plataforma");

                    b.Property<int>("id_user")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<string>("link_acesso")
                        .HasColumnType("longtext")
                        .HasColumnName("link_acesso");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("id_plataforma");

                    b.HasIndex("id_user");

                    b.ToTable("usuario_conexao");
                });

            modelBuilder.Entity("back_end.Models.UsuarioConquista", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dt_desbloqueio")
                        .HasColumnType("date");

                    b.Property<int>("id_conquista")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_conquista");

                    b.HasIndex("id_user");

                    b.ToTable("UsuarioConquistas");
                });

            modelBuilder.Entity("back_end.Models.Catalogo", b =>
                {
                    b.HasOne("back_end.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("id_jpjogos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_end.Models.Conquista", b =>
                {
                    b.HasOne("back_end.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("id_jp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("back_end.Models.JogoPlataforma", b =>
                {
                    b.HasOne("back_end.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("id_jogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("id_plataforma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("back_end.Models.Seguidor", b =>
                {
                    b.HasOne("back_end.Models.Usuario", "UsuarioSeguidor")
                        .WithMany()
                        .HasForeignKey("id_seguidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.Models.Usuario", "UsuarioSeguindo")
                        .WithMany()
                        .HasForeignKey("id_seguindo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSeguidor");

                    b.Navigation("UsuarioSeguindo");
                });

            modelBuilder.Entity("back_end.Models.UsuarioConexao", b =>
                {
                    b.HasOne("back_end.Models.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("id_plataforma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_end.Models.UsuarioConquista", b =>
                {
                    b.HasOne("back_end.Models.Conquista", "Conquista")
                        .WithMany()
                        .HasForeignKey("id_conquista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
